name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: "Ruby ${{ matrix.ruby_version }} (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true 
      matrix:
        os:
        - "ubuntu"
        - "windows-latest"
        ruby_version:
        - "2.6"
        - "2.7"
        - "3.0"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: "Set up Ruby ${{ matrix.ruby_version }}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.tuby_version }}
          bundler-cache: true
      - name: Execute Unit Tests
        run:  bash script/test --force-color

  style_check:
    name: "Style Check (Ruby ${{ matrix.ruby_version }})"
    runs-on: "ubuntu-"
    strategy:
      fail-fast: true
      matrix:
        ruby_version:
        - 2.6
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: "Set up Ruby ${{ matrix.ruby_version }}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: 
        run:  bash script/fmt
